version: "3"
services:
  mongo:
    image: mongo:latest
    container_name: mongo_manager_tasks
    ports:
      - "27017:27017"
    volumes:
      - data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: manager_tasks
volumes:
  data:
