export enum ActionFormReducerNames {
  SET_TITLE = "SET_TITLE",
  SET_DESCRIPTION = "SET_DESCRIPTION",
  SET_DATE = "SET_DATE",
  SET_COMPLETED = "SET_COMPLETED",
  SET_IMPORTANT = "SET_IMPORTANT",
}
