import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ClerkProvider, auth } from "@clerk/nextjs";
import "../styles/globals.css";
import { Sidebar } from "@/components";
import { GlobalsStyleProvider, ContextProviders } from "@/providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Manager Tasks",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const { userId } = auth();
  return (
    <ClerkProvider>
      <html lang="en">
        <head>
          <link
            rel="stylesheet"
            href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css"
            integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA=="
            crossOrigin="anonymous"
            referrerPolicy="no-referrer"
          />
        </head>
        <body className={inter.className}>
          <ContextProviders>
            <GlobalsStyleProvider>
              {userId && <Sidebar />}
              <div className="w-full"> {children}</div>
            </GlobalsStyleProvider>
          </ContextProviders>
        </body>
      </html>
    </ClerkProvider>
  );
}
